<?php

declare(strict_types=1);

namespace CWM\BuildTools\Dev;

use PDO;
use PDOException;
use RuntimeException;

/**
 * A Joomla install's database, resolved from its own `configuration.php`.
 *
 * "Read configuration.php, open a connection, know the prefix" is the primitive
 * every release-harness script needs and nobody owned. It was hand-rolled in
 * twelve files across Proclaim and CWMLivingWord, and they did not even agree on
 * a driver — six used `mysqli_*` and the rest PDO — so escaping, error handling
 * and "did the connection fail" differed per file. The canonical version already
 * existed inside `ExtensionVerifier` and was private to it.
 *
 * ## `configuration.php` wins over `build.properties`
 *
 * `InstallConfig` also carries a `db` block, read from `build.properties`, and a
 * caller holding one may reasonably expect it to be used. It is not, and that is
 * deliberate: `configuration.php` is what the running site actually connects
 * with. `build.properties` records what a developer told the tooling months ago,
 * and when the two disagree the site is right — a harness that resets tables
 * through the wrong credentials either fails confusingly or, worse, succeeds
 * against the wrong database.
 *
 * Callers who genuinely want the configured credentials should build their own
 * PDO from `InstallConfig`; this class is specifically "the database this site
 * is using".
 *
 * ## Parsing is separate from connecting
 *
 * {@see readConfig()} is pure and takes a path, so it is tested against fixture
 * `configuration.php` files. {@see connect()} is the part that needs a live
 * server. Keeping them apart is what makes any of this testable — the reason the
 * original was never covered is that it could only be reached by standing up a
 * Joomla install first.
 *
 * `configuration.php` is generated by Joomla and follows a deterministic
 * `public $key = 'value';` shape, so it is parsed as text rather than by
 * including it. Including it would execute arbitrary PHP from disk and define a
 * `JConfig` class in this process.
 */
final class TestSite
{
    private ?PDO $pdo = null;

    /** Resolved lazily; see {@see schemaName()}. */
    private ?string $schemaName = null;

    /**
     * @param  string  $path    Absolute path to the Joomla document root.
     * @param  array{host: string, user: string, password: string, db: string, dbprefix: string, driver: string}  $config
     *         Parsed connection values from that install's configuration.php.
     */
    private function __construct(
        public readonly string $path,
        private readonly array $config,
    ) {
    }

    /**
     * Build one from a Joomla document root.
     *
     * Nothing connects yet — {@see db()} does that on first use, so a caller
     * that only wants the prefix, or that is deciding whether a site is usable
     * at all, does not pay for a connection.
     *
     * @throws RuntimeException When the path is not a directory, or
     *                          configuration.php is missing or unreadable.
     */
    public static function fromPath(string $path): self
    {
        if (!is_dir($path)) {
            throw new RuntimeException("Joomla path does not exist: {$path}");
        }

        $config = self::readConfig($path);

        if ($config === null) {
            throw new RuntimeException("Could not read database settings from {$path}/configuration.php");
        }

        return new self($path, $config);
    }

    /**
     * Build one from an install declared in build.properties.
     *
     * The install supplies the path only; the credentials still come from the
     * site's own configuration.php. See the class docblock for why.
     *
     * @throws RuntimeException As {@see fromPath()}.
     */
    public static function fromInstall(InstallConfig $install): self
    {
        return self::fromPath($install->path);
    }

    /**
     * Build one around a connection that is already open.
     *
     * For callers holding a PDO of their own — and for tests, which can then
     * exercise the query layer against an in-memory database instead of
     * asserting on generated SQL strings. Nothing is read from disk, so `$path`
     * is descriptive only, used in error messages.
     */
    public static function fromPdo(PDO $pdo, string $prefix, string $path = '(connection supplied)'): self
    {
        $site = new self($path, [
            'host'     => '',
            'user'     => '',
            'password' => '',
            'db'       => '',
            'dbprefix' => $prefix,
            'driver'   => (string) $pdo->getAttribute(PDO::ATTR_DRIVER_NAME),
        ]);

        $site->pdo = $pdo;

        return $site;
    }

    /**
     * The site's table prefix, e.g. `jos_`.
     *
     * Defaults to `jos_` when configuration.php omits it, matching Joomla's own
     * default rather than guessing from the schema.
     */
    public function prefix(): string
    {
        return $this->config['dbprefix'];
    }

    /** The database name the site connects to. */
    public function database(): string
    {
        return $this->config['db'];
    }

    /**
     * The PDO driver this site uses: `mysql` or `pgsql`.
     *
     * Read from `dbtype` in configuration.php. Callers running SQL that is not
     * portable — and most schema DDL is not — should branch on this rather than
     * assume, which is the assumption every hand-rolled copy made silently.
     */
    public function driver(): string
    {
        return $this->config['driver'];
    }

    /** Whether this site runs on PostgreSQL. */
    public function isPostgres(): bool
    {
        return $this->driver() === 'pgsql';
    }

    /**
     * The DSN for this site's driver.
     *
     * `charset=utf8mb4` is MySQL-only; PostgreSQL takes the encoding from the
     * database itself, and passing an unknown DSN parameter to it is an error
     * rather than something ignored.
     */
    private function dsn(): string
    {
        $host = $this->config['host'];
        $db   = $this->config['db'];

        if ($this->driver() === 'pgsql') {
            // Joomla writes host:port into the same field for both drivers.
            [$hostname, $port] = array_pad(explode(':', $host, 2), 2, null);

            return 'pgsql:host=' . $hostname
                . ($port !== null ? ';port=' . $port : '')
                . ';dbname=' . $db;
        }

        return 'mysql:host=' . $host . ';dbname=' . $db . ';charset=utf8mb4';
    }

    /**
     * The schema name `information_schema` queries should filter on.
     *
     * The two databases disagree about what a "schema" is. In MySQL it is the
     * database, so the database name is the filter. In PostgreSQL a database
     * holds many schemas and Joomla's tables live in whichever is first on the
     * search path — usually `public`, but not necessarily, so it is asked
     * rather than assumed.
     *
     * Filtering matters: without it, `information_schema` answers about every
     * schema on the server, and a table of the same name in another database
     * reads as this site's.
     */
    private function schemaName(): string
    {
        if ($this->schemaName !== null) {
            return $this->schemaName;
        }

        if ($this->driver() === 'pgsql') {
            $current = $this->db()->query('SELECT current_schema()')?->fetchColumn();

            return $this->schemaName = is_string($current) ? $current : 'public';
        }

        // fromPdo() carries no database name; ask the connection instead.
        if ($this->config['db'] !== '') {
            return $this->schemaName = $this->config['db'];
        }

        $current = $this->db()->query('SELECT DATABASE()')?->fetchColumn();

        return $this->schemaName = is_string($current) ? $current : '';
    }

    /**
     * Prefix a Joomla table token: `#__extensions` -> `jos_extensions`.
     *
     * Every caller was building these by concatenation, which is where a
     * missing prefix or a doubled one comes from. Taking the token the schema
     * files already use keeps queries readable and the prefix in one place.
     */
    public function table(string $token): string
    {
        return str_replace('#__', $this->prefix(), $token);
    }

    /**
     * The connection, opened on first call and reused after.
     *
     * Errors are exceptions: `PDO::ERRMODE_EXCEPTION` is set so a failed query
     * cannot be mistaken for an empty result. Half the hand-rolled copies used
     * `mysqli_query`, which returns `false` on failure, and a caller that only
     * checked for an empty row set read a broken query as "not installed".
     *
     * @throws RuntimeException When the connection cannot be opened.
     */
    public function db(): PDO
    {
        if ($this->pdo instanceof PDO) {
            return $this->pdo;
        }

        try {
            $this->pdo = new PDO(
                $this->dsn(),
                $this->config['user'],
                $this->config['password'],
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION],
            );
        } catch (PDOException $e) {
            throw new RuntimeException(
                "Could not connect to {$this->config['db']} at {$this->config['host']} "
                . "(credentials from {$this->path}/configuration.php): " . $e->getMessage(),
                0,
                $e,
            );
        }

        return $this->pdo;
    }

    /**
     * Whether a table exists in this site's schema.
     *
     * Takes a `#__`-prefixed token. Used by harnesses deciding whether a
     * migration landed, and by reset paths that must not `DROP` what was never
     * created.
     */
    public function hasTable(string $token): bool
    {
        $stmt = $this->db()->prepare(
            'SELECT 1 FROM information_schema.tables WHERE table_schema = ? AND table_name = ?'
        );
        $stmt->execute([$this->schemaName(), $this->table($token)]);

        return $stmt->fetchColumn() !== false;
    }

    /**
     * Whether a column exists on a table.
     *
     * Column names cannot be bound, and neither can table names, so both are
     * interpolated — the inputs are project-controlled schema tokens, per the
     * build-tools threat model, not user input.
     */
    public function hasColumn(string $token, string $column): bool
    {
        $stmt = $this->db()->prepare(
            'SELECT 1 FROM information_schema.columns '
            . 'WHERE table_schema = ? AND table_name = ? AND column_name = ?'
        );
        $stmt->execute([$this->schemaName(), $this->table($token), $column]);

        return $stmt->fetchColumn() !== false;
    }

    /**
     * Read the database settings out of `<path>/configuration.php`.
     *
     * Pure: it takes a path and returns values, so it is tested against fixture
     * files rather than a live install.
     *
     * @return array{host: string, user: string, password: string, db: string, dbprefix: string, driver: string}|null
     *         Null when the file is absent, unreadable, or names no database.
     */
    public static function readConfig(string $joomlaPath): ?array
    {
        $configFile = $joomlaPath . '/configuration.php';

        if (!is_file($configFile)) {
            return null;
        }

        $content = @file_get_contents($configFile);

        if ($content === false) {
            return null;
        }

        $values = [];

        if (preg_match_all('/public\s+\$(\w+)\s*=\s*([\'"])(.*?)\2\s*;/s', $content, $m, PREG_SET_ORDER)) {
            foreach ($m as $match) {
                $values[$match[1]] = self::unescapePhpString($match[3], $match[2]);
            }
        }

        // No database name means this is not a configured install — a freshly
        // unpacked Joomla, or a file that parsed to nothing. Either way there is
        // nothing to connect to, and saying so is more useful than connecting
        // to a default and reporting an empty schema.
        if (!isset($values['db'])) {
            return null;
        }

        return [
            'host'     => $values['host'] ?? 'localhost',
            'user'     => $values['user'] ?? '',
            'password' => $values['password'] ?? '',
            'db'       => $values['db'],
            'dbprefix' => $values['dbprefix'] ?? 'jos_',
            'driver'   => self::normaliseDriver($values['dbtype'] ?? 'mysqli'),
        ];
    }

    /**
     * Map Joomla's `dbtype` onto a PDO driver name.
     *
     * Joomla writes `mysqli` (and historically `mysql`) for MySQL and MariaDB,
     * and `pgsql` (sometimes spelled `postgresql`) for PostgreSQL. PDO knows
     * `mysql` and `pgsql`.
     *
     * An unrecognised value falls back to `mysql` rather than throwing: every
     * CWM site is MySQL today, and refusing to open a connection over a dbtype
     * this mapping has not seen would break working installs to guard against a
     * database nobody is using. The fallback is visible via {@see driver()} so a
     * caller that cares can check.
     */
    private static function normaliseDriver(string $dbtype): string
    {
        return match (strtolower($dbtype)) {
            'pgsql', 'postgresql' => 'pgsql',
            default               => 'mysql',
        };
    }

    /**
     * Undo PHP's string escaping for the quote style the value was written in.
     *
     * Single-quoted values escape only `\` and `'`; double-quoted ones take the
     * full C-style set. A password containing a backslash is the case that
     * makes this matter.
     */
    private static function unescapePhpString(string $raw, string $quote): string
    {
        if ($quote === "'") {
            return strtr($raw, ['\\\\' => '\\', "\\'" => "'"]);
        }

        return stripcslashes($raw);
    }
}
